<a href="https://colab.research.google.com/github/Alexsoundra/data-science-bootcamp/blob/main/01_wprowadzenie/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
pip install numpy

In [3]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3 , 2.3, 1.4])

In [15]:
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

In [19]:
x = np.array([[1, 2], [-3, 1]])

In [20]:
print(x)

[[ 1  2]
 [-3  1]]


In [21]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [24]:
x = np.array([[1, 2, 3], [4, 2, 1]])

In [25]:
x.shape

(2, 3)

In [26]:
x = np.array([
              [[4, 3 ,1]
               ,[3, 1, 2]],
              [[4, 1, 3], 
               [4, 2, 1]]])
x




array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(2, 2, 3)

In [29]:
A =np.array([1, 2, 3])
A.dtype

dtype('int64')

In [30]:
A =np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [31]:
A =np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [32]:
A =np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [33]:
A =np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [34]:
A

array([1, 2, 3])

In [35]:
A = np.array([True, False])

In [36]:
A.dtype

dtype('bool')

In [37]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
 np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [45]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [47]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [48]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [49]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [50]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [55]:
A + B

array([6, 0, 7, 4])

In [56]:
A - B

array([0, 2, 1, 0])

In [57]:
A * B

array([ 9, -1, 12,  4])

In [58]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [59]:
A + 3

array([6, 4, 7, 5])

In [60]:
2 * A

array([6, 2, 8, 4])

In [61]:
A + 3*B

array([12, -2, 13,  8])

In [62]:
np.add(A, B)

array([6, 0, 7, 4])

In [64]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6,0], [-1, 2]])
print(x)
print(y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [65]:
x * y


array([[6, 0],
       [2, 0]])

In [66]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [67]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [69]:
np.random.seed(0)

In [70]:
np.random.randn()

1.764052345967664

In [71]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [72]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [73]:
np.random.rand()

0.1965823616800535

In [74]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [75]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [76]:
np.random.randint(10)

3

In [77]:
np.random.randint(low=10, high=101)

56

In [78]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [80]:
np.random.choice([4, 2, 1, 3, 5])

3

In [82]:
np.random.choice(['python', 'sql', 'java'])

'python'

In [83]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.random.shuffle(data)

In [85]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

In [86]:
np.exp(1)

2.718281828459045

In [88]:
np.sqrt(9)

3.0

In [90]:
np.all([2, 3, 0])

False

In [91]:
np.any([1, 2, 1])

True

In [92]:
bool(1.3)

True

In [94]:
A = np.random.rand(5)
A

array([0.58127287, 0.88173536, 0.69253159, 0.72525428, 0.50132438])

In [96]:
np.argmax(A)

1

In [97]:
A[np.argmax(A)]

0.8817353618548528

In [98]:
np.argmin(A)

4

In [99]:
np.argsort(A)

array([4, 0, 2, 3, 1])

In [100]:
np.max(A)

0.8817353618548528

In [101]:
np.min(A)

0.5013243819267023

In [102]:
np.mean(A)

0.676423697262964

In [103]:
np.median(A)

0.6925315900777659

In [104]:
np.std(A)

0.13000786074672221

In [106]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [107]:
A[2]

2

In [108]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [109]:
A[:2]

array([0, 1])

In [110]:
A[-1]

19

In [111]:
A[10:15]

array([10, 11, 12, 13, 14])

In [123]:
A.reshape(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [125]:
A.shape

(20,)

In [126]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [127]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
A.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [131]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [132]:
A[ A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [133]:
np.bitwise_and( A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [134]:
A[np.bitwise_and( A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [135]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [136]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])